In [1]:
import pandas as pd
df = pd.read_csv("../data/Library_Usage.csv",
                low_memory=False
                )
#eine erste Übersicht verschaffen:
df

In [2]:
# 1. Wie viele Merkmale besitzt der Datensatz? Die Merkmale entsprechen den Spalten
len(df.columns)

11

In [3]:
# 2.Wie groß ist die Stichprobengröße des Datensatzes?
len(df)

450359

In [4]:
# 3. Wer oder was sind die Merkmalsträger?

 Bibliothekskunden der SF Public Library.

In [5]:
# 4. Von wann bis wann wurden die Daten erhoben?

Aus dem Datensatz lässt sich herauslesen, dass die ersten Nutzeregistrierungen 2003 waren Einführung Bibliothekssystem), die letzten 2022. Der Datensatz selbst wurde zuletzt 2023 aktualisiert (laut Webseite).

Weiterführende Informationen sind auf der Webseite verfügbar: https://data.sfgov.org/Culture-and-Recreation/Library-Usage/qzz6-2jup/about_data

In [6]:
df['Year Patron Registered'].value_counts(normalize=True)

2023    0.132654
2022    0.115015
2003    0.088927
2021    0.072678
2019    0.072502
2020    0.065870
2017    0.064515
2018    0.062939
2016    0.048117
2015    0.043767
2014    0.033917
2013    0.028750
2012    0.027600
2011    0.026841
2009    0.024580
2010    0.024363
2008    0.021705
2007    0.014033
2006    0.011302
2005    0.010263
2004    0.009661
Name: Year Patron Registered, dtype: float64

In [7]:
# 5. Wie lässt sich die Grundgesamtheit beschreiben? Handelt es sich um eine Vollerhebung?

Grundgesamtheit sind alle Bibliothekskunden der San Francisco Library. Wahrscheinlich handelt es sich um eine Vollerhebung. Es lässt sich diskutieren, ob die Grundgesamtheit größer gefasst werden kann (z.B. alle Kunden von Bibliotheken in den USA oder alle Kunden von öffentlichen Bibliotheken). Was meinst Du: sind die Daten repräsentativ für diese Grundgesamtheiten?

In [8]:
# 6. Welche Merkmale sind stetig? Welche diskret?
#
#Aus der Beschreibung der Merkmale des Datensatzes aber auch einfach bereits mit
#df
#lässt sich erkennen, dass nur die Variablen 'Total Checkouts' und 'Total Renewals' stetig sind. 
#Alle anderen sind diskret

In [9]:
# 7. Welchem Skalenniveau entsprechen die einzelnen Merkmale (Nominal-, Ordinal- oder Metrische Skala)? 
#
# Siehe wieder 
#df

In [10]:
# Ordinal: 'Age Range'

In [11]:
# Metrisch: 'Total Checkouts', 'Total Renewals', 'Circulation Active Year', 'Year Patron registered'

In [12]:
# Nominal: 'Patron Type Code', 'Patron Type Definition', 'Home Library Code', 
# 'Home Library Definition', 'Circulation Active Month', 'Notice Preference Code', 
# 'Notice Preference Definition', 'Provided Email Address', 'Within San Francisco County'

In [13]:
# 8. Enthält der Datensatz fehlende Werte? Ja, z.B. 'Circulation Active Year'

In [29]:
df['Circulation Active Year']

0         2022
1         2023
2         2024
3         2022
4         2024
          ...
450354    Null
450355    2022
450356    2022
450357    2022
450358    2023
Name: Circulation Active Year, Length: 450359, dtype: object

In [33]:
#dennoch werden die Werte "Null" nicht als fehlende Werte, sondern als Text erkannt:
df.isna().sum()

Patron Type Definition          0
Total Checkouts                 0
Total Renewals                  0
Age Range                       0
Home Library Definition         0
Circulation Active Month        0
Circulation Active Year         0
Notice Preference Definition    0
Provided Email Address          0
Year Patron Registered          0
Within San Francisco County     0
dtype: int64

In [34]:
#daher entsprechend beim Einlesen definieren:
df = pd.read_csv("../data/Library_Usage.csv",
                low_memory=False, na_values="Null"
                )

In [35]:
df.isna().sum()

Patron Type Definition              0
Total Checkouts                     0
Total Renewals                      0
Age Range                         510
Home Library Definition            30
Circulation Active Month        40317
Circulation Active Year         40317
Notice Preference Definition     3315
Provided Email Address              0
Year Patron Registered              0
Within San Francisco County       221
dtype: int64

In [36]:
# 9. Handelt es sich um Querschnitts-, Längsschnitss- oder Paneldaten? 
#
# Querschnittsdaten

In [26]:
row_filter = (df['Age Range'] == '20 to 24 years') 
df.loc[row_filter]

,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
3,Welcome,1,1,20 to 24 years,Richmond,Aug,2022,Email,True,2022,False
6,Adult,0,0,20 to 24 years,Main,Feb,2024,Email,True,2023,False
308,Adult,0,0,20 to 24 years,Main,Feb,2024,Email,True,2022,False
323,Adult,62,1,20 to 24 years,Main,Aug,2023,Email,True,2015,False
338,Adult,0,0,20 to 24 years,Main,Oct,2023,Print,False,2023,False
...,...,...,...,...,...,...,...,...,...,...,...
450186,Adult,0,0,20 to 24 years,Ingleside,Null,Null,Email,True,2022,Null
450255,Teen,1,0,20 to 24 years,Richmond,Feb,2024,Email,False,2023,Null
450284,Digital Access Card,0,0,20 to 24 years,Main,Dec,2021,Print,False,2021,Null
450304,Digital Access Card,0,0,20 to 24 years,Potrero,Oct,2022,Email,False,2022,Null
450330,Digital Access Card,0,0,20 to 24 years,Glen Park,Apr,2022,Print,False,2022,Null

In [37]:
df['Patron Type Definition'].value_counts()

Adult                  284671
Juvenile                57486
Senior                  49025
Teen                    41042
Welcome                  9412
Digital Access Card      4558
Teacher Card             3415
Retired Staff             211
Visitor                   184
At User Adult             126
Library By Mail           116
At User Senior             73
At User Welcome            14
At User Teen                8
Business                    7
At User Juvenile            6
Bibliocommons               5
Name: Patron Type Definition, dtype: int64

In [38]:
df['Age Range'].value_counts()

25 to 34 years       95278
35 to 44 years       85669
10 to 19 years       67758
45 to 54 years       49820
0 to 9 years         33180
65 to 74 years       32455
20 to 24 years       27145
75 years and over    20721
55 to 59 years       19735
60 to 64 years       18088
Name: Age Range, dtype: int64

In [39]:


pd.crosstab(
    df['Patron Type Definition'],
    df['Notice Preference Definition'],
    margins=True,
    normalize=1
)

Notice Preference Definition     Email     Phone     Print       All
Patron Type Definition
Adult                         0.658182  0.370230  0.444515  0.634763
At User Adult                 0.000259  0.000410  0.001118  0.000282
At User Juvenile              0.000012  0.000000  0.000000  0.000011
At User Senior                0.000127  0.000536  0.000479  0.000161
At User Teen                  0.000020  0.000000  0.000000  0.000018
At User Welcome               0.000032  0.000032  0.000000  0.000031
Bibliocommons                 0.000002  0.000095  0.000160  0.000011
Business                      0.000017  0.000000  0.000000  0.000016
Digital Access Card           0.006874  0.009713  0.067220  0.007921
Juvenile                      0.121162  0.183664  0.203736  0.126753
Library By Mail               0.000242  0.000410  0.000639  0.000259
Retired Staff                 0.000486  0.000252  0.000639  0.000472
Senior                        0.100080  0.217471  0.167811  0.109356
Teacher Card                  0.008055  0.002870  0.003353  0.007621
Teen                          0.084210  0.191170  0.058917  0.091443
Visitor                       0.000420  0.000158  0.000639  0.000405
Welcome                       0.019818  0.022990  0.050774  0.020477

In [40]:
pd.crosstab(
    df['Age Range'],
    df['Notice Preference Definition'],
    margins=True,
    normalize=1
)

Notice Preference Definition     Email     Phone     Print       All
Age Range
0 to 9 years                  0.073601  0.049863  0.165276  0.073196
10 to 19 years                0.137327  0.331177  0.100770  0.150573
20 to 24 years                0.060065  0.067851  0.042202  0.060368
25 to 34 years                0.222431  0.084419  0.160462  0.211772
35 to 44 years                0.199696  0.077382  0.155327  0.190397
45 to 54 years                0.114524  0.066968  0.095635  0.110886
55 to 59 years                0.044261  0.039795  0.044769  0.043951
60 to 64 years                0.039379  0.049768  0.047978  0.040236
65 to 74 years                0.068491  0.116767  0.100610  0.072365
75 years and over             0.040225  0.116010  0.086970  0.046256

In [41]:
pd.crosstab(
    df['Patron Type Definition'],
    df['Age Range'],
    margins=True,
    normalize=1
)

Age Range,0 to 9 years,10 to 19 years,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 years and over,All
Patron Type Definition,,,,,,,,,,,
Adult,0.002230,0.030048,0.943968,0.938811,0.945161,0.950662,0.953332,0.955440,0.087321,0.005405,0.632561
At User Adult,0.000000,0.000015,0.000258,0.000136,0.000303,0.000542,0.001064,0.001272,0.000185,0.000048,0.000278
At User Juvenile,0.000090,0.000044,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000013
At User Senior,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001325,0.001448,0.000162
At User Teen,0.000000,0.000118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000018
At User Welcome,0.000000,0.000044,0.000037,0.000021,0.000047,0.000040,0.000000,0.000055,0.000000,0.000048,0.000031
Bibliocommons,0.000000,0.000000,0.000000,0.000052,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000011
Business,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000048,0.000002
Digital Access Card,0.000181,0.001638,0.010978,0.014746,0.016680,0.013589,0.009678,0.008735,0.005238,0.002992,0.010019
Juvenile,0.994967,0.360725,0.000147,0.000063,0.000117,0.000060,0.000000,0.000000,0.000031,0.000048,0.127776
Library By Mail,0.000000,0.000000,0.000074,0.000084,0.000105,0.000100,0.000253,0.000332,0.000739,0.002751,0.000258
Retired Staff,0.000000,0.000000,0.000000,0.000010,0.000000,0.000000,0.000456,0.000719,0.002342,0.001834,0.000305
Senior,0.000000,0.000000,0.000000,0.000000,0.000023,0.000080,0.000963,0.003594,0.884055,0.975966,0.108937
Teacher Card,0.002049,0.000059,0.004163,0.008029,0.011078,0.013268,0.013631,0.009454,0.005053,0.001351,0.007096
Teen,0.000090,0.605390,0.000295,0.000010,0.000012,0.000020,0.000000,0.000000,0.000000,0.000000,0.091217
Visitor,0.000090,0.000074,0.000958,0.000546,0.000374,0.000422,0.000507,0.000719,0.000401,0.000434,0.000409
Welcome,0.000301,0.001845,0.039123,0.037490,0.026100,0.021216,0.020117,0.019682,0.013311,0.007625,0.020907